# Generated by Django 5.1.2 on 2025-06-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bolten', '0003_alter_newsitem_news_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='news_published_date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
