# Generated by Django 5.1.2 on 2025-06-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bolten', '0004_alter_newsitem_news_published_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='link',
            field=models.URLField(max_length=500),
        ),
    ]
